import React, { useCallback, useMemo, useState } from 'react';
import { LanguageContext } from './language-context';

const translations = {
  tr: {
    welcome: 'Hoş Geldiniz',
    systemTitle: 'Malzeme İzlenebilirlik Sistemi (MTS)',
    username: 'Kullanıcı Adı',
    usernamePlaceholder: 'Örn. kullanici_adi',
    password: 'Parola',
    login: 'Sisteme Giriş Yap',
    loggingIn: 'Giriş Yapılıyor...',
    loginFailed: 'Kullanıcı adı veya parola hatalı. Lütfen yeniden deneyin.',
    logout: 'Çıkış Yap',
    system: 'Sistem',
    overview: 'Genel Bakış',
    chemicals: 'Kimyasal Kataloğu',
    batches: 'Hammadde Partileri',
    addresses: 'Depo Rafları',
      units: 'Stok Birimleri',
    qrLabels: 'QR Barkod Etiketleri',
    relocationTasks: 'Raf Taşıma Görevleri',
    language: 'Dil / Language',
    apiErrors: {
      INSUFFICIENT_RACK_CAPACITY: '{storageType} depolama türünde yeterli raf kapasitesi bulunamadı.',
      RACK_STORAGE_TYPE_INCOMPATIBLE: 'Raf, mevcut stokların depolama türüyle uyumsuz hale getirilemez.',
      CANNOT_DELETE_NON_EMPTY_RACK: 'Rafta aktif stok bulunduğu için bu raf silinemez!',
      INVALID_RACK_CAPACITY: 'Raf kapasitesi sıfırdan büyük olmalıdır.',
      RACK_CAPACITY_BELOW_OCCUPANCY: 'Yeni kapasite mevcut aktif stoktan küçük olamaz.',
    },
    safetyAssistant: {
      title: 'İSG & MSDS Asistanı',
      subtitle: 'Resmi MSDS dokümanları üzerinden yerel yapay zeka destekli acil durum rehberi.',
      selectChemical: 'Kimyasal Seçiniz',
      scopeTitle: 'Doküman kapsamı',
      scopeNote: 'Yanıtlar yalnızca seçili kimyasalın resmi MSDS bölümünden üretilir.',
      quickTitle: 'Hızlı acil durum soruları',
      quickDescription: 'Operasyon anında sık kullanılan hazır sorulardan birini seçin.',
      askTitle: 'Operatör sorusu',
      askPlaceholder: 'Bir acil durum veya güvenlik sorusu sorun...',
      askButton: 'Yapay Zekaya Sor',
      loadingText: 'MSDS dokümanı taranıyor ve cevap üretiliyor...',
      assistantResponse: 'ASİSTAN YANITI',
      verifiedBadge: 'MSDS doğrulandı',
      reviewBadge: 'Kontrol gerekli',
      sourcePrefix: 'Kaynak:',
      readyTitle: 'Güvenlik sorunuz yanıtlanmaya hazır.',
      readyDescription: 'Bir hazır soru seçin veya operatör sorunuzu yukarıya yazın.',
      chemicalLoadFailed: 'Kimyasal listesi yüklenemedi.',
      fallbackChemicalNote: 'Varsayılan olarak CC-202 kullanılabilir.',
      emptyQuestion: 'Lütfen operatör sorusunu yazın.',
      answerFailed: 'Asistan yanıt veremedi. Lütfen Ollama servisinin açık olduğunu kontrol edin.',
      quickChips: {
        fire: 'Alev alırsa su ile söndürülür mü?',
        firstAid: 'Cilde temas ederse ilk yardım prosedürü nedir?',
        spill: 'Varil delinirse dökülmeye nasıl müdahale edilir?',
        storage: 'Güvenli depolama ve raf sıcaklık şartları nelerdir?',
      },
    },

    // Dashboard
    dashboardTitle: 'Sistem Genel Görünümü',
    dashboardDesc: 'Fabrika genelindeki kimyasal malzeme hareketlerini anlık olarak izleyin ve yönetin.',
    inStockDrums: 'Stoktaki Variller',
    totalConsumed: 'Toplam Tüketilen',
    pendingOps: 'Bekleyen İşlemler',
    expiredBlocked: 'Süresi Dolan / Bloke',
    recentConsumptionLogs: 'Son Malzeme Tüketim Kayıtları',
    time: 'Zaman',
    action: 'İşlem',
    barcode: 'Barkod',
    chemical: 'Kimyasal',
    operator: 'Operatör',
    noTransactionsYet: 'Henüz işlem bulunmuyor',
    noTransactionsDesc: 'Operatörler kimyasal varilleri okuttukça tüketim kayıtları burada görüntülenecektir.',
    consumed: 'TÜKETİLDİ',
    unknown: 'Bilinmiyor',

    // QR Label Manager
    qrLabelTitle: 'QR Barkod Etiketleri',
    qrLabelSubtitle: 'Önce parti etiketini, ardından partiye ait varil etiketlerini yazdırın.',
    rawMaterialBatch: 'Hammadde Partileri',
    selectBatchPlaceholder: 'Parti numarası veya kimyasal adıyla arayın…',
    noBatchSelected: 'Henüz bir parti seçilmedi',
    noBatchSelectedDesc: 'Etiketleri görüntülemek ve yazdırmak için lütfen yukarıdan bir hammadde partisi seçiniz.',
    selectAll: 'Tümünü Seç',
    selectAvailableOnly: 'Sadece Müsaitleri Seç',
    selectedCount: 'Seçilen',
    labelsCount: 'etiket',
    printSelected: 'Etiketi Yazdır',
    batchOpeningLabel: 'Parti açılış etiketi',
    batchOpeningLabelDesc: 'Mobil terminalde önce bu etiket okutulur; ardından yalnızca bu partiye ait variller işleme alınabilir.',
    printBatchLabel: 'Batch Etiketini Yazdır',
      available: 'Müsait',
    expired: 'Süresi Dolmuş',
    depleted: 'Tüketildi',
    unitConsumedNotification: '{barcode} mobil terminal tarafından tüketildi.',
    expDate: 'SKT',

    // Relocation Tasks
    relocationTitle: 'Raf Taşıma Görevleri',
    relocationSubtitle: 'Görevi planlayın; fiziksel taşımayı mobil terminalde çift QR doğrulamasıyla tamamlayın.',
    compatibleTargetShelf: 'Uyumlu Hedef Raf',
    createTask: 'Görev Oluştur',
    cancelTask: 'İptal Et',
    taskPending: 'BEKLİYOR',
    taskCompleted: 'TAMAMLANDI',
    taskCancelled: 'İPTAL EDİLDİ',
    source: 'Kaynak',
    target: 'Hedef',
    noTasksInStatus: 'Bu durumda görev bulunmuyor.',
    completeOnMobile: 'Mobilde tamamlanır',

    addressesTitle: 'Depo Rafları',
    rackCode: 'Raf Kodu',
    capacity: 'Kapasite',
    storageType: 'Depolama Türü',
    general: 'Genel',
    solvent: 'Solvent',
    flammable: 'Yanıcı',
    corrosive: 'Korozif',
    paint: 'Boya',
    saveCreate: 'Kaydet / Oluştur',
    currentOccupancy: 'Mevcut Doluluk',
    availableCapacity: 'Boş Kapasite',
    label: 'Etiket',
    unlimited: 'Sınırsız',
    printQr: 'QR Yazdır',
    addressLoadFailed: 'Depo rafları yüklenemedi.',
    addressCreated: 'Depo rafı oluşturuldu.',
    addressCreateFailed: 'Depo rafı oluşturulamadı.',
    allowPopups: 'Etiketi yazdırmak için açılır pencerelere izin veriniz.',
    addressTypeUpdated: 'depolama türü güncellendi.',
    addressTypeUpdateFailed: 'Depolama türü güncellenemedi.',
    rackDeleteConfirm: 'Bu rafı silmek istediğinize emin misiniz?',
    rackDeleted: 'Raf başarıyla silindi.',
    rackDeleteFailed: 'Raf silinemedi.',
    rackCapacityRequired: 'Kapasite',
    targetRackLabel: 'HEDEF RAF ETİKETİ',
    storage: 'Depolama',

    batchesTitle: 'Hammadde Partileri',
    searchBatch: 'Parti Ara',
    searchBatchPlaceholder: 'Parti no, kimyasal kodu/adı veya tedarikçi',
    search: 'Ara',
    clear: 'Temizle',
    batchNo: 'Parti No',
    supplier: 'Tedarikçi',
    initialQuantity: 'Başlangıç Miktarı',
    expirationDate: 'Son Kullanma Tarihi',
    selectChemical: 'Kimyasal Seçiniz',
    batchLoadFailed: 'Hammadde partileri yüklenemedi.',
    batchCreated: 'Hammadde partisi oluşturuldu.',
    batchCreateFailed: 'Hammadde partisi oluşturulamadı.',

    chemicalsTitle: 'Kimyasal Kataloğu',
    chemicalCode: 'Kimyasal Kodu',
    chemicalName: 'Kimyasal Adı',
    description: 'Açıklama',
    msdsUrl: 'MSDS URL',
    code: 'Kod',
    name: 'Ad',
    status: 'Durum',
    active: 'Aktif',
    stopped: 'Durduruldu',
    delete: 'Sil',
    chemicalLoadFailed: 'Kimyasal kataloğu yüklenemedi.',
    chemicalCreated: 'Kimyasal kaydı oluşturuldu.',
    chemicalCreateFailed: 'Kimyasal kaydı oluşturulamadı.',
    deleteChemicalConfirm: 'kodlu kimyasal silinsin mi?',
    chemicalDeleted: 'Kimyasal kaydı silindi.',
    chemicalDeleteFailed: 'Kimyasal kaydı silinemedi.',
    chemicalTypeUpdated: 'depolama türü güncellendi.',
    chemicalTypeUpdateFailed: 'Depolama türü güncellenemedi.',

    unitsTitle: 'Stok Birimleri',
    searchUnit: 'Stok Birimi Ara',
    searchUnitPlaceholder: 'Barkod, parti, kimyasal veya raf kodu',
    selectRack: 'Depo Rafı Seçiniz',
    listRackUnits: 'Raftakileri Listele',
    batch: 'Parti',
    rack: 'Raf',
    unitLoadFailed: 'Depo rafları yüklenemedi.',
    unitNotFound: 'Aramanızla eşleşen stok birimi bulunamadı.',
    unitSearchFailed: 'Stok birimi bulunamadı.',
    rackUnitsLoadFailed: 'Raf stoğu yüklenemedi.',
    consumedStatus: 'Tüketildi',
    notAssigned: 'Rafa Atanmamış',

    relocationPageTitle: 'Raf Taşıma Görevleri',
    relocationPageDescription: 'Görevi planlayın; fiziksel taşımayı mobil terminalde çift QR doğrulamasıyla tamamlayın.',
    compatibleTargetRack: 'Uyumlu Hedef Raf',
    taskCreated: 'Görev oluşturuldu. Mobil terminalde Unit ve hedef raf okutularak tamamlanmalıdır.',
    taskCreateFailed: 'Görev oluşturulamadı.',
    tasksLoadFailed: 'Görevler yüklenemedi.',
    compatibleRackNotFound: 'Uyumlu ve kapasitesi müsait başka raf bulunamadı.',
    unitLookupFailed: 'Birim sorgulanamadı.',
    cancelTaskFailed: 'Görev iptal edilemedi.',
    taskPendingLabel: 'BEKLİYOR',
    taskCompletedLabel: 'TAMAMLANDI',
    taskCancelledLabel: 'İPTAL EDİLDİ',
    loading: 'Yükleniyor…',
    task: 'Görev',
    cancel: 'İptal Et',
    completedOnMobile: 'Mobilde tamamlanır',
    currentRack: 'Mevcut raf',
    unlimitedCapacity: 'Sınırsız',
    emptyCapacity: 'boş yer',

    unexpectedError: 'Beklenmeyen bir hata oluştu.',
    reloadPage: 'Sayfayı Yenile',
    actions: 'İşlemler',
    noLabels: 'Bu partiye ait birim etiketi bulunmuyor.',
    selectLabel: 'etiketini seç',
    previewQr: 'QR Önizle',
    qrPreview: 'QR Önizleme',
    printThisLabel: 'Bu Etiketi Yazdır',
    close: 'Kapat',
    labelsLoadFailed: 'Hammadde partileri yüklenemedi.',
    batchLabelsLoadFailed: 'Parti etiketleri yüklenemedi.',
    batchSummaryLabel: 'Parti',
    chemicalSummaryLabel: 'Kimyasal',
    landingLogin: 'Giriş Yap',
    landingReady: 'MTS v2.0 kullanıma hazır',
    landingTitle: 'Uçtan Uca Malzeme İzlenebilirliği',
    landingDescription: 'Kimyasal tüketimini izleyin, depo raf hareketlerini yönetin ve malzeme güvenliğini tek bir endüstriyel platformda sağlayın.',
    accessSystem: 'Sisteme Eriş',
    viewDocs: 'Dokümantasyonu Görüntüle',
    liveFeed: 'CANLI AKIŞ',
    liveTanker: 'Tanker yükleme işlemi tamamlandı',
    liveBatch: 'B-993 malzeme partisi tüketildi',
    liveStock: 'Stok limiti uyarısı: Aseton',
    minutesAgo: 'dakika önce',
    hourAgo: 'saat önce',
    landingFeaturesTitle: 'Modern depo operasyonları için tasarlandı.',
    featureQr: 'QR Barkod Takibi',
    featureQrDesc: 'Malzemelerin konum ve durum bilgilerini QR barkodlar ile anlık olarak izleyin.',
    featureStock: 'Anlık Stok Yönetimi',
    featureStockDesc: 'Stok seviyelerini, tüketilen birimleri ve son kullanma tarihlerini kolayca yönetin.',
    featureSecurity: 'Kurumsal Güvenlik',
    featureSecurityDesc: 'Rol tabanlı erişim kontrolü ve güvenli oturum yönetimiyle korunan çalışma ortamı.',
    featureInsights: 'Operasyonel İçgörüler',
    featureInsightsDesc: 'Malzeme tüketim eğilimlerini ve kritik stok hareketlerini tek ekrandan değerlendirin.',
  },
  en: {
    welcome: 'Welcome',
    systemTitle: 'Material Traceability System (MTS)',
    username: 'Username',
    usernamePlaceholder: 'e.g. username',
    password: 'Password',
    login: 'Log In',
    loggingIn: 'Logging in...',
    loginFailed: 'Invalid username or password. Please try again.',
    logout: 'Log Out',
    system: 'System',
    overview: 'Overview',
    chemicals: 'Chemical Catalog',
    batches: 'Raw Material Batches',
    addresses: 'Storage Racks',
    units: 'Stock Units',
    qrLabels: 'QR Barcode Labels',
    relocationTasks: 'Relocation Tasks',
    language: 'Language',
    apiErrors: {
      INSUFFICIENT_RACK_CAPACITY: 'No rack has sufficient capacity for the {storageType} storage type.',
      RACK_STORAGE_TYPE_INCOMPATIBLE: 'The rack cannot be changed to an incompatible storage type for its current stock.',
      CANNOT_DELETE_NON_EMPTY_RACK: 'Cannot delete rack because it contains active stock!',
      INVALID_RACK_CAPACITY: 'Rack capacity must be a positive integer.',
      RACK_CAPACITY_BELOW_OCCUPANCY: 'New capacity cannot be lower than current active stock.',
    },
    safetyAssistant: {
      title: 'EHS & MSDS Assistant',
      subtitle: 'Local AI-powered emergency safety guidance based on official MSDS documents.',
      selectChemical: 'Select Chemical',
      scopeTitle: 'Document scope',
      scopeNote: 'Responses are generated only from the official MSDS section of the selected chemical.',
      quickTitle: 'Quick emergency questions',
      quickDescription: 'Select a frequently used question for an operation in progress.',
      askTitle: 'Operator question',
      askPlaceholder: 'Ask an emergency or safety question...',
      askButton: 'Ask AI',
      loadingText: 'Scanning MSDS document and generating response...',
      assistantResponse: 'ASSISTANT RESPONSE',
      verifiedBadge: 'MSDS Verified',
      reviewBadge: 'Review required',
      sourcePrefix: 'Source:',
      readyTitle: 'Your safety question is ready to be answered.',
      readyDescription: 'Select a quick question or write your operator question above.',
      chemicalLoadFailed: 'Chemical list could not be loaded.',
      fallbackChemicalNote: 'CC-202 remains available as the default.',
      emptyQuestion: 'Please enter the operator question.',
      answerFailed: 'The assistant could not respond. Please check that the Ollama service is running.',
      quickChips: {
        fire: 'Can it be extinguished with water if ignited?',
        firstAid: 'What is the first aid procedure for skin contact?',
        spill: 'How to handle spills if a barrel is punctured?',
        storage: 'What are the safe storage and shelf temperature conditions?',
      },
    },

    // Dashboard
    dashboardTitle: 'System Overview',
    dashboardDesc: 'Monitor and manage chemical material movements across the plant in real time.',
    inStockDrums: 'In-Stock Drums',
    totalConsumed: 'Total Consumed',
    pendingOps: 'Pending Operations',
    expiredBlocked: 'Expired / Blocked',
    recentConsumptionLogs: 'Recent Material Consumption Logs',
    time: 'Time',
    action: 'Action',
    barcode: 'Barcode',
    chemical: 'Chemical',
    operator: 'Operator',
    noTransactionsYet: 'No transactions yet',
    noTransactionsDesc: 'Consumption logs will appear here as operators scan chemical drums.',
    consumed: 'CONSUMED',
    unknown: 'Unknown',

    // QR Label Manager
    qrLabelTitle: 'QR Barcode Labels',
    qrLabelSubtitle: 'First print the batch label, then print the individual drum labels for that batch.',
    rawMaterialBatch: 'Raw Material Batches',
    selectBatchPlaceholder: 'Search by batch number or chemical name…',
    noBatchSelected: 'No batch selected yet',
    noBatchSelectedDesc: 'Please select a raw material batch above to view and print labels.',
    selectAll: 'Select All',
    selectAvailableOnly: 'Select Available Only',
    selectedCount: 'Selected',
    labelsCount: 'labels',
    printSelected: 'Print Labels',
    batchOpeningLabel: 'Batch Opening Label',
    batchOpeningLabelDesc: 'Scan this label first on the mobile terminal; only drums from this batch will be accepted for processing.',
    printBatchLabel: 'Print Batch Label',
        available: 'Available',
    expired: 'Expired',
    depleted: 'Depleted',
    unitConsumedNotification: '{barcode} was consumed by the mobile terminal.',
    expDate: 'Exp Date',

    // Relocation Tasks
    relocationTitle: 'Relocation Tasks',
    relocationSubtitle: 'Plan relocation tasks; complete physical transfers on the mobile terminal via dual-QR verification.',
    newTask: 'New Task',
    stockUnitBarcode: 'Stock Unit Barcode',
    findUnit: 'Find Unit',
    compatibleTargetShelf: 'Compatible Target Rack',
    createTask: 'Create Task',
    cancelTask: 'Cancel Task',
    taskPending: 'PENDING',
    taskCompleted: 'COMPLETED',
    taskCancelled: 'CANCELLED',
    source: 'Source',
    target: 'Target',
    noTasksInStatus: 'No tasks found in this status.',
    completeOnMobile: 'Completed on mobile',
    addressesTitle: 'Storage Racks',
    rackCode: 'Rack Code',
    capacity: 'Capacity',
    storageType: 'Storage Type',
    general: 'General',
    solvent: 'Solvent',
    flammable: 'Flammable',
    corrosive: 'Corrosive',
    paint: 'Paint',
    saveCreate: 'Save / Create',
    currentOccupancy: 'Current Occupancy',
    availableCapacity: 'Available Capacity',
    label: 'Label',
    unlimited: 'Unlimited',
    printQr: 'Print QR',
    addressLoadFailed: 'Storage racks could not be loaded.',
    addressCreated: 'Storage rack created.',
    addressCreateFailed: 'Storage rack could not be created.',
    allowPopups: 'Allow pop-ups to print the label.',
    addressTypeUpdated: 'storage type updated.',
    addressTypeUpdateFailed: 'Storage type could not be updated.',
    rackDeleteConfirm: 'Are you sure you want to delete this rack?',
    rackDeleted: 'Rack deleted successfully.',
    rackDeleteFailed: 'Rack could not be deleted.',
    rackCapacityRequired: 'Capacity',
    targetRackLabel: 'TARGET RACK LABEL',
    storage: 'Storage',
    batchesTitle: 'Raw Material Batches',
    searchBatch: 'Search Batches',
    searchBatchPlaceholder: 'Batch number, chemical code/name or supplier',
    search: 'Search',
    clear: 'Clear',
    batchNo: 'Batch No.',
    supplier: 'Supplier',
    initialQuantity: 'Initial Quantity',
    expirationDate: 'Expiration Date',
    selectChemical: 'Select Chemical',
    batchLoadFailed: 'Raw material batches could not be loaded.',
    batchCreated: 'Raw material batch created.',
    batchCreateFailed: 'Raw material batch could not be created.',
    chemicalsTitle: 'Chemical Catalog',
    chemicalCode: 'Chemical Code',
    chemicalName: 'Chemical Name',
    description: 'Description',
    msdsUrl: 'MSDS URL',
    code: 'Code',
    name: 'Name',
    status: 'Status',
    active: 'Active',
    stopped: 'Stopped',
    delete: 'Delete',
    chemicalLoadFailed: 'Chemical catalog could not be loaded.',
    chemicalCreated: 'Chemical record created.',
    chemicalCreateFailed: 'Chemical record could not be created.',
    deleteChemicalConfirm: 'chemical should be deleted?',
    chemicalDeleted: 'Chemical record deleted.',
    chemicalDeleteFailed: 'Chemical record could not be deleted.',
    chemicalTypeUpdated: 'storage type updated.',
    chemicalTypeUpdateFailed: 'Storage type could not be updated.',
    unitsTitle: 'Stock Units',
    searchUnit: 'Search Stock Units',
    searchUnitPlaceholder: 'Barcode, batch, chemical or rack code',
    selectRack: 'Select Storage Rack',
    listRackUnits: 'List Rack Units',
    batch: 'Batch',
    rack: 'Rack',
    unitLoadFailed: 'Storage racks could not be loaded.',
    unitNotFound: 'No stock unit matched your search.',
    unitSearchFailed: 'Stock units could not be found.',
    rackUnitsLoadFailed: 'Rack stock could not be loaded.',
    consumedStatus: 'Consumed',
    notAssigned: 'Not Assigned to Rack',
    relocationPageTitle: 'Relocation Tasks',
    relocationPageDescription: 'Plan the task; complete the physical transfer on the mobile terminal with dual QR verification.',
    compatibleTargetRack: 'Compatible Target Rack',
    taskCreated: 'Task created. Scan the unit and target rack on the mobile terminal to complete it.',
    taskCreateFailed: 'Task could not be created.',
    tasksLoadFailed: 'Tasks could not be loaded.',
    compatibleRackNotFound: 'No compatible rack with available capacity was found.',
    unitLookupFailed: 'Unit could not be found.',
    cancelTaskFailed: 'Task could not be cancelled.',
    taskPendingLabel: 'PENDING',
    taskCompletedLabel: 'COMPLETED',
    taskCancelledLabel: 'CANCELLED',
    loading: 'Loading…',
    task: 'Task',
    cancel: 'Cancel',
    completedOnMobile: 'Completed on mobile',
    currentRack: 'Current rack',
    unlimitedCapacity: 'Unlimited',
    emptyCapacity: 'spaces available',
    unexpectedError: 'An unexpected error occurred.',
    reloadPage: 'Reload Page',
    actions: 'Actions',
    noLabels: 'No unit labels found for this batch.',
    selectLabel: 'select label',
    previewQr: 'Preview QR',
    qrPreview: 'QR Preview',
    printThisLabel: 'Print This Label',
    close: 'Close',
    labelsLoadFailed: 'Raw material batches could not be loaded.',
    batchLabelsLoadFailed: 'Batch labels could not be loaded.',
    batchSummaryLabel: 'Batch',
    chemicalSummaryLabel: 'Chemical',
    landingLogin: 'Log In',
    landingReady: 'MTS v2.0 is ready',
    landingTitle: 'End-to-End Material Traceability',
    landingDescription: 'Monitor chemical consumption, manage storage rack movements and ensure material safety in one industrial platform.',
    accessSystem: 'Access System',
    viewDocs: 'View Documentation',
    liveFeed: 'LIVE FEED',
    liveTanker: 'Tanker loading completed',
    liveBatch: 'Batch B-993 consumed',
    liveStock: 'Stock limit warning: Acetone',
    minutesAgo: 'minutes ago',
    hourAgo: 'hour ago',
    landingFeaturesTitle: 'Designed for modern warehouse operations.',
    featureQr: 'QR Barcode Tracking',
    featureQrDesc: 'Monitor material location and status in real time with QR barcodes.',
    featureStock: 'Real-Time Inventory',
    featureStockDesc: 'Manage stock levels, consumed units and expiration dates with ease.',
    featureSecurity: 'Enterprise Security',
    featureSecurityDesc: 'A protected workspace with role-based access control and secure sessions.',
    featureInsights: 'Operational Insights',
    featureInsightsDesc: 'Review material consumption trends and critical stock movements in one view.',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem('app_lang') || 'tr');

  const setLanguage = useCallback((lang) => {
    localStorage.setItem('app_lang', lang);
    setLanguageState(lang);
  }, []);

  const t = useCallback((key) => {
    const resolve = (dictionary) => key.split('.').reduce((value, part) => value?.[part], dictionary);
    return resolve(translations[language]) || resolve(translations.tr) || key;
  }, [language]);
  const contextValue = useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}
